sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - pypy3
  - 3.3
  - 3.4
  - 3.5
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-xlwt
            - python-xlrd
            - python-coverage
            - python-nose
            - python-mock
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - pip install nose nose-cov codecov coverage pyexcel
  - pip install setuptools>=17.1
script:
  - python setup.py install
  - make test
after_success:
  codecov
