sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - pypy3
  - 3.3
  - 3.4
  - 3.5
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-xlwt
            - python-xlrd
            - python-coverage
            - python-nose
            - python-mock
before_install:
  - pip install https://github.com/pyexcel/pyexcel-io/archive/master.zip
  - pip install https://github.com/pyexcel/pyexcel/archive/master.zip
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - if [[ -f rnd_requirements.txt ]]; then pip install -r rnd_requirements.txt; fi
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
